# Generated by Django 2.1.3 on 2018-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_sentence',
            field=models.TextField(blank=True, max_length=600),
        ),
    ]
