# Generated by Django 2.1.3 on 2018-12-10 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery')),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('pub_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
