# Generated by Django 2.1.3 on 2018-12-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='messages',
            field=models.BooleanField(default=True),
        ),
    ]
