# Generated by Django 2.1.3 on 2018-12-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='messages',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
