# Generated by Django 2.1.3 on 2018-11-29 12:39

from django.db import migrations, models
import django.db.models.deletion
import positions.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('sort', positions.fields.PositionField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_type', models.IntegerField()),
                ('nav_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='navigation',
            name='subsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.Subsite'),
        ),
    ]
