# Generated by Django 2.1.3 on 2018-11-29 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationType',
        ),
        migrations.AlterField(
            model_name='subsite',
            name='pub_date',
            field=models.DateField(default=datetime.date(2018, 11, 29)),
        ),
    ]
