# Generated by Django 2.1.3 on 2018-11-29 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20181129_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='url',
            field=models.SlugField(default='article', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subsite',
            name='pub_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
