# Generated by Django 2.1.3 on 2018-12-05 08:11

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20181205_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('lead_sentence', models.CharField(blank=True, max_length=600)),
                ('content', tinymce.models.HTMLField()),
                ('pub_date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
