# Generated by Django 2.1.3 on 2018-12-06 13:48

import colorful.fields
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_ad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('logo_image', models.ImageField(blank=True, upload_to='')),
                ('logo_text', models.CharField(max_length=40)),
                ('baner', models.ImageField(blank=True, upload_to='')),
                ('baner_text', tinymce.models.HTMLField(blank=True)),
                ('background_color', colorful.fields.RGBColorField()),
                ('accent_color_1', colorful.fields.RGBColorField()),
                ('accent_color_2', colorful.fields.RGBColorField()),
                ('main_color_1', colorful.fields.RGBColorField()),
                ('main_color_2', colorful.fields.RGBColorField()),
            ],
        ),
    ]
