# Generated by Django 2.1.3 on 2018-12-06 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20181206_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='big_font_size',
            field=models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(36)]),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='normal_font_size',
            field=models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(18)]),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='small_font_size',
            field=models.IntegerField(default=11, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
