# Generated by Django 2.1.3 on 2018-12-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20181206_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appconfig',
            old_name='baner',
            new_name='baner_image',
        ),
    ]
