# Generated by Django 2.1.3 on 2018-12-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20181206_1517'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
