# Generated by Django 2.1.3 on 2018-12-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_delete_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
