# Generated by Django 2.1.3 on 2018-12-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='subsite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subsite.Subsite'),
        ),
        migrations.DeleteModel(
            name='Subsite',
        ),
    ]
