# Generated by Django 2.1.3 on 2018-12-09 13:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20181209_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='homepage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.Navigation'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='fn',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='navigation',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='big_font_size',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(36)]),
        ),
    ]
