# Generated by Django 2.1.3 on 2018-12-09 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20181209_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='fn',
            new_name='application',
        ),
    ]
