# Generated by Django 2.1.3 on 2018-12-12 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20181209_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigation',
            name='subsite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subsite.Subsite'),
        ),
    ]
