# Generated by Django 2.1.3 on 2018-12-12 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='menu'),
        ),
        migrations.AddField(
            model_name='price',
            name='size',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='menu.Size'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='extra_info',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='size',
            name='amount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='unit_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
