# Generated by Django 2.1.3 on 2018-12-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_auto_20181213_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['sort']},
        ),
        migrations.AddField(
            model_name='size',
            name='sort',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
